# Abstand zwischen Partikeln in Blöcken
particle-spacing: 0.5

# Partikeltyp für die Linien (Minecraft Particle Enum)
particle-type: VILLAGER_HAPPY

# Tick-Intervall für Line-Follow (10 = alle 0,5 Sekunden)
linefollow-ticks: 5

# Standardfarbe oder Farbeffekte für Partikel (optional, je nach Particle)
particle-color: "#04bbdf"

# Maximale Anzahl gespeicherter Punkte pro Route
max-points: 10000000000000000

# Standard-Name für neue Routen, falls kein Name angegeben wird
default-route-name: "NeueRoute"

# Line-Follow automatisch starten beim Editieren
auto-linefollow-on-edit: false
