name: Build RoutePlugin (Spigot 1.21.4)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git wget

      - name: Download BuildTools
        run: |
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot 1.21.4
        run: |
          java -jar BuildTools.jar --rev 1.21.4
          mkdir -p ~/.m2/repository/org/spigotmc/spigot-api/1.21.4-R0.1-SNAPSHOT
          cp spigot-1.21.4-R0.1-SNAPSHOT-api.jar ~/.m2/repository/org/spigotmc/spigot-api/1.21.4-R0.1-SNAPSHOT/spigot-api-1.21.4-R0.1-SNAPSHOT.jar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Plugin with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: RoutePlugin
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built JAR
        uses: actions/download-artifact@v3
        with:
          name: RoutePlugin
          path: .

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "RoutePlugin v${{ github.run_number }}"
          files: "*.jar"
          draft: false
          prerelease: false
